-- M10_0: Enterprise rate limits on plan_limits
ALTER TABLE "plan_limits" ADD COLUMN IF NOT EXISTS "rpm" INTEGER NOT NULL DEFAULT 120;
ALTER TABLE "plan_limits" ADD COLUMN IF NOT EXISTS "daily_requests" INTEGER NOT NULL DEFAULT 10000;
ALTER TABLE "plan_limits" ADD COLUMN IF NOT EXISTS "monthly_requests" INTEGER NOT NULL DEFAULT 300000;
ALTER TABLE "plan_limits" ADD COLUMN IF NOT EXISTS "monthly_tokens" BIGINT NOT NULL DEFAULT 10000000;
ALTER TABLE "plan_limits" ADD COLUMN IF NOT EXISTS "monthly_storage_mb" INTEGER NOT NULL DEFAULT 5120;
