-- AlterTable
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "balance_rub" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "spent_rub" DECIMAL(14,6) NOT NULL DEFAULT 0;
