module.exports = {
  apps: [
    {
      name: 'crm-al-tokens-api',
      cwd: '/var/www/crm-al-tokens/apps/api',
      script: 'dist/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', APP_ROLE: 'api' },
    },
    {
      name: 'crm-al-worker-knowledge',
      cwd: '/var/www/crm-al-tokens/apps/api',
      script: 'dist/src/worker.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', APP_ROLE: 'worker-knowledge' },
    },
    {
      name: 'crm-al-worker-workflow',
      cwd: '/var/www/crm-al-tokens/apps/api',
      script: 'dist/src/worker.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', APP_ROLE: 'worker-workflow' },
    },
    {
      name: 'crm-al-worker-memory',
      cwd: '/var/www/crm-al-tokens/apps/api',
      script: 'dist/src/worker.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', APP_ROLE: 'worker-memory' },
    },
    {
      name: 'crm-al-worker-integrations',
      cwd: '/var/www/crm-al-tokens/apps/api',
      script: 'dist/src/worker.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', APP_ROLE: 'worker-integrations' },
    },
    {
      name: 'crm-al-worker-tools',
      cwd: '/var/www/crm-al-tokens/apps/api',
      script: 'dist/src/worker.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', APP_ROLE: 'worker-tools' },
    },
  ],
};
