-- M10_1: Audit hardening — traceId, organizationId, extended actions
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "trace_id" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "organization_id" TEXT;

CREATE INDEX IF NOT EXISTS "audit_logs_trace_id_idx" ON "audit_logs"("trace_id");
CREATE INDEX IF NOT EXISTS "audit_logs_organization_id_created_at_idx" ON "audit_logs"("organization_id", "created_at");

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'KNOWLEDGE_INGEST';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'KNOWLEDGE_RETRIEVAL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEMORY_READ';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEMORY_WRITE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WORKFLOW_STARTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WORKFLOW_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WORKFLOW_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MARKETPLACE_PUBLISH';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MARKETPLACE_INSTALL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INTEGRATION_EVENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CRM_MUTATION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TOOL_EXECUTION';
